/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tabla.periodica.FrameTablaPeriodica;

/**
 *
 * @author Ana Belen
 */
public class FrameElemento extends javax.swing.JFrame {

    /**
     * Creates new form FrameElemento
     */
    public FrameElemento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JLabel();
        jSimbolo1 = new javax.swing.JLabel();
        jClass1 = new javax.swing.JLabel();
        jNAtomico1 = new javax.swing.JLabel();
        jConfElect = new javax.swing.JLabel();
        jNMasico = new javax.swing.JLabel();
        jNOxidacion = new javax.swing.JLabel();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(144, 97, 194));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Symbol:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Atomic Number: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Atomic Mass:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Oxidation Numbers:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Electronic Configuration:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, -1));

        jNombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jNombre1.setText(".");
        jPanel1.add(jNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 20));

        jSimbolo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSimbolo1.setForeground(new java.awt.Color(255, 255, 255));
        jSimbolo1.setText(".");
        jPanel1.add(jSimbolo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 20));

        jClass1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jClass1.setForeground(new java.awt.Color(255, 255, 255));
        jClass1.setText(".");
        jPanel1.add(jClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 350, 20));

        jNAtomico1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNAtomico1.setForeground(new java.awt.Color(255, 255, 255));
        jNAtomico1.setText(".");
        jPanel1.add(jNAtomico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 20));

        jConfElect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jConfElect.setForeground(new java.awt.Color(255, 255, 255));
        jConfElect.setText(".");
        jPanel1.add(jConfElect, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 20));

        jNMasico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNMasico.setForeground(new java.awt.Color(255, 255, 255));
        jNMasico.setText(".");
        jPanel1.add(jNMasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 20));

        jNOxidacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNOxidacion.setForeground(new java.awt.Color(255, 255, 255));
        jNOxidacion.setText(".");
        jPanel1.add(jNOxidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameElemento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jClass1;
    public static javax.swing.JLabel jConfElect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jNAtomico1;
    public static javax.swing.JLabel jNMasico;
    public static javax.swing.JLabel jNOxidacion;
    public static javax.swing.JLabel jNombre1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jSimbolo1;
    // End of variables declaration//GEN-END:variables
}
